// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.22.3
// source: base/actor.proto

package base

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Actor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=LastName,proto3" json:"LastName,omitempty"`
	BirthDate     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=BirthDate,proto3" json:"BirthDate,omitempty"`
	DeathDate     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=DeathDate,proto3,oneof" json:"DeathDate,omitempty"` // Pointer since it could be nil for living actors
	Nationality   string                 `protobuf:"bytes,6,opt,name=Nationality,proto3" json:"Nationality,omitempty"`
	Biography     string                 `protobuf:"bytes,7,opt,name=Biography,proto3" json:"Biography,omitempty"`
	ImageURL      string                 `protobuf:"bytes,8,opt,name=ImageURL,proto3" json:"ImageURL,omitempty"`       // URL to actor's image
	Filmography   []*FilmographyEntry    `protobuf:"bytes,9,rep,name=Filmography,proto3" json:"Filmography,omitempty"` // Movies they participated in with their roles
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	IsDeleted     bool                   `protobuf:"varint,12,opt,name=IsDeleted,proto3" json:"IsDeleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Actor) Reset() {
	*x = Actor{}
	mi := &file_base_actor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Actor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Actor) ProtoMessage() {}

func (x *Actor) ProtoReflect() protoreflect.Message {
	mi := &file_base_actor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Actor.ProtoReflect.Descriptor instead.
func (*Actor) Descriptor() ([]byte, []int) {
	return file_base_actor_proto_rawDescGZIP(), []int{0}
}

func (x *Actor) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Actor) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Actor) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Actor) GetBirthDate() *timestamppb.Timestamp {
	if x != nil {
		return x.BirthDate
	}
	return nil
}

func (x *Actor) GetDeathDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DeathDate
	}
	return nil
}

func (x *Actor) GetNationality() string {
	if x != nil {
		return x.Nationality
	}
	return ""
}

func (x *Actor) GetBiography() string {
	if x != nil {
		return x.Biography
	}
	return ""
}

func (x *Actor) GetImageURL() string {
	if x != nil {
		return x.ImageURL
	}
	return ""
}

func (x *Actor) GetFilmography() []*FilmographyEntry {
	if x != nil {
		return x.Filmography
	}
	return nil
}

func (x *Actor) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Actor) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Actor) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

type FilmographyEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieID       string                 `protobuf:"bytes,1,opt,name=MovieID,proto3" json:"MovieID,omitempty"`
	Character     string                 `protobuf:"bytes,2,opt,name=Character,proto3" json:"Character,omitempty"` // The character they played (empty for crew)
	Role          string                 `protobuf:"bytes,3,opt,name=Role,proto3" json:"Role,omitempty"`           // "Actor" or crew role (Director, Producer, etc.)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilmographyEntry) Reset() {
	*x = FilmographyEntry{}
	mi := &file_base_actor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilmographyEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilmographyEntry) ProtoMessage() {}

func (x *FilmographyEntry) ProtoReflect() protoreflect.Message {
	mi := &file_base_actor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilmographyEntry.ProtoReflect.Descriptor instead.
func (*FilmographyEntry) Descriptor() ([]byte, []int) {
	return file_base_actor_proto_rawDescGZIP(), []int{1}
}

func (x *FilmographyEntry) GetMovieID() string {
	if x != nil {
		return x.MovieID
	}
	return ""
}

func (x *FilmographyEntry) GetCharacter() string {
	if x != nil {
		return x.Character
	}
	return ""
}

func (x *FilmographyEntry) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

var File_base_actor_proto protoreflect.FileDescriptor

const file_base_actor_proto_rawDesc = "" +
	"\n" +
	"\x10base/actor.proto\x12\n" +
	"actor.base\x1a\x1fgoogle/protobuf/timestamp.proto\"\x86\x04\n" +
	"\x05Actor\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x1c\n" +
	"\tFirstName\x18\x02 \x01(\tR\tFirstName\x12\x1a\n" +
	"\bLastName\x18\x03 \x01(\tR\bLastName\x128\n" +
	"\tBirthDate\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tBirthDate\x12=\n" +
	"\tDeathDate\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tDeathDate\x88\x01\x01\x12 \n" +
	"\vNationality\x18\x06 \x01(\tR\vNationality\x12\x1c\n" +
	"\tBiography\x18\a \x01(\tR\tBiography\x12\x1a\n" +
	"\bImageURL\x18\b \x01(\tR\bImageURL\x12>\n" +
	"\vFilmography\x18\t \x03(\v2\x1c.actor.base.FilmographyEntryR\vFilmography\x128\n" +
	"\tCreatedAt\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\x12\x1c\n" +
	"\tIsDeleted\x18\f \x01(\bR\tIsDeletedB\f\n" +
	"\n" +
	"_DeathDate\"^\n" +
	"\x10FilmographyEntry\x12\x18\n" +
	"\aMovieID\x18\x01 \x01(\tR\aMovieID\x12\x1c\n" +
	"\tCharacter\x18\x02 \x01(\tR\tCharacter\x12\x12\n" +
	"\x04Role\x18\x03 \x01(\tR\x04RoleB8Z6github.com/sorawaslocked/ap2final_protos_gen/base;baseb\x06proto3"

var (
	file_base_actor_proto_rawDescOnce sync.Once
	file_base_actor_proto_rawDescData []byte
)

func file_base_actor_proto_rawDescGZIP() []byte {
	file_base_actor_proto_rawDescOnce.Do(func() {
		file_base_actor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_base_actor_proto_rawDesc), len(file_base_actor_proto_rawDesc)))
	})
	return file_base_actor_proto_rawDescData
}

var file_base_actor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_base_actor_proto_goTypes = []any{
	(*Actor)(nil),                 // 0: actor.base.Actor
	(*FilmographyEntry)(nil),      // 1: actor.base.FilmographyEntry
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_base_actor_proto_depIdxs = []int32{
	2, // 0: actor.base.Actor.BirthDate:type_name -> google.protobuf.Timestamp
	2, // 1: actor.base.Actor.DeathDate:type_name -> google.protobuf.Timestamp
	1, // 2: actor.base.Actor.Filmography:type_name -> actor.base.FilmographyEntry
	2, // 3: actor.base.Actor.CreatedAt:type_name -> google.protobuf.Timestamp
	2, // 4: actor.base.Actor.UpdatedAt:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_base_actor_proto_init() }
func file_base_actor_proto_init() {
	if File_base_actor_proto != nil {
		return
	}
	file_base_actor_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_base_actor_proto_rawDesc), len(file_base_actor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_base_actor_proto_goTypes,
		DependencyIndexes: file_base_actor_proto_depIdxs,
		MessageInfos:      file_base_actor_proto_msgTypes,
	}.Build()
	File_base_actor_proto = out.File
	file_base_actor_proto_goTypes = nil
	file_base_actor_proto_depIdxs = nil
}
