name: Generate ProtoBuf

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Generator Repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Install Protobuf Compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Install Go Protobuf Tools
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.33.0
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.3.0
          echo "GOPATH bin: $(go env GOPATH)/bin"
          export PATH="$PATH:$(go env GOPATH)/bin"

      - name: Clone Proto Files Repository
        run: |
          git clone https://github.com/sorawaslocked/ap2final_protos proto-src

      - name: Generate Go Code from Proto Files
        run: |
          cd proto-src

          echo "Cleaning up old generated files..."
          find . -name "*.pb.go" -delete

          echo "Generating .pb.go and _grpc.pb.go files..."
          find . -name "*.proto" -print0 | xargs -0 -n1 protoc -I. --go_out=paths=source_relative:. --go-grpc_out=paths=source_relative:.

          echo "Generated files:"
          find . -name "*.pb.go"

          if [ -z "$(find . -name '*.pb.go')" ]; then
            echo "Error: No .pb.go files were generated."
            exit 1
          fi

      - name: Push Generated Code to Gen Repo
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git clone https://github.com/sorawaslocked/ap2final_protos_gen gen-repo

          # Copy all generated .pb.go files preserving folder structure
          cd proto-src
          find . -name "*.pb.go" | while read file; do
            target="../gen-repo/$(dirname "$file")"
            mkdir -p "$target"
            cp "$file" "$target/"
          done

          cd ../gen-repo

          git config --global user.name "sorawaslocked"
          git config --global user.email "133684349+sorawaslocked@users.noreply.github.com"

          git add .

          if git diff --cached --quiet; then
            echo "No changes to commit. Skipping commit and push."
          else
            git commit -m "Regenerate proto Go files"
            NEW_TAG="v0.0.$(date +%s)"
            git tag "$NEW_TAG"
            git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/sorawaslocked/ap2final_protos_gen.git
            git push origin main --follow-tags
          fi